### ISSUE TITLE
Choice of Language

### ISSUE THREAD

**Issue by lakindu2002** [writergate/topic-planner#7]
Is there a specific reason we are using JavaScript? 
TypeScript would be better in my opinion. It would help improve readability into your code.

Suggestions ?

**Comment by Anuja-2000** [comment]
Most of learning materials are in JavaScript ayye. That's why we chose it.

**Comment by lakindu2002** [comment]
I think it would be better if we can use typescript. It isn't hard actually.
https://www.typescriptlang.org/

@Anuja-2000

**Comment by Anuja-2000** [comment]
ok ayye we'll try to move to typescript. then we have to create a new project from scratch ayye isn't it. Can we know your thoughts @lakindu2002
